"""Signal 1 — Groq LLM classification (semantic).

Asks llama-3.3-70b-versatile to holistically judge whether text reads as
AI-generated and return a calibrated probability (NOT a binary yes/no). The
model is instructed to lean toward the middle of the range when genuinely
unsure, which feeds the system's "uncertain" band downstream.

Output: {"ai_probability": float 0-1, "rationale": str}
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    """Lazily construct the Groq client so importing this module is cheap."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


SYSTEM_PROMPT = """\
You are an AI-content detection signal for a creative-writing platform. Your job
is to estimate the probability that a passage of text was generated by an AI
language model rather than written by a human.

Judge holistically: tonal evenness, generic or "safe" phrasing, uniform hedging,
lack of idiosyncrasy, and overly tidy structure are signals of AI generation.
Personal voice, abrupt shifts, opinion, slang, and irregularity are signals of
human writing.

Be calibrated and humble. A false positive (calling a human's work AI) is worse
than a false negative. If you are genuinely unsure, return a probability in the
middle of the range (around 0.4-0.7) rather than committing to a confident
verdict. Reserve probabilities above 0.85 or below 0.15 for clear-cut cases.

Respond ONLY with a JSON object of exactly this shape:
{"ai_probability": <float between 0 and 1>, "rationale": "<one sentence>"}
"""


def score_llm(text):
    """Return Signal 1's assessment of `text`.

    Returns {"ai_probability": float, "rationale": str}. On API/parse failure
    returns a neutral 0.5 with an error rationale so the pipeline degrades
    gracefully into "uncertain" rather than crashing.
    """
    try:
        resp = _get_client().chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        prob = float(data.get("ai_probability"))
        # Clamp into [0, 1] to defend against a misbehaving response.
        prob = max(0.0, min(1.0, prob))
        rationale = str(data.get("rationale", "")).strip()
        return {"ai_probability": prob, "rationale": rationale}
    except Exception as exc:  # noqa: BLE001 - degrade gracefully
        return {
            "ai_probability": 0.5,
            "rationale": f"LLM signal unavailable ({type(exc).__name__}); "
                         "defaulting to uncertain.",
        }


if __name__ == "__main__":
    # Standalone test: run a couple of inputs and inspect raw output.
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift "
            "in modern society. It is important to note that while the benefits "
            "of AI are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium "
            "in it and i was thirsty for like three hours after."
        ),
    }
    for label, sample in samples.items():
        print(f"\n=== {label} ===")
        print(json.dumps(score_llm(sample), indent=2))
